# Generated by Django 3.2 on 2021-04-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='replacement_link',
            field=models.URLField(null=True),
        ),
    ]
