# Generated by Django 3.2 on 2021-04-19 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_item_replacement_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='replacement_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='replacement_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
